### ISSUE TITLE
AddAzureFunctionsGraphQL error with hotchocolate V13

### ISSUE THREAD

**Issue by Hgaray** [cajuncoding/GraphQL.AzureFunctionsProxy#6]
builder.Services.AddAzureFunctionsGraphQL(options => { options.AzureFunctionsRoutePath = "/graphql"; }); get an error after migrate to HotChocolate v13

![image](https://user-images.githubusercontent.com/41797160/233212191-ab750508-a7f3-4207-a90e-97cf8f270410.png)

**Comment by cajuncoding** [comment]
Yes that is expected, the readme clearly states this is supported for v11 & v12…

However, I do need to update the Readme, because as of v13 we have now integrated this into HC as an OOTB feature with additional optimizations since it’s now part of the core code base now 😃. 

So for v13 you’ll need to migrate (it’s very easy) to use the OOTB version that was introduced here:

https://chillicream.com/blog/2023/02/08/new-in-hot-chocolate-13#azure-functions

**Comment by cajuncoding** [comment]
Thanks for the reminder that I needed cross post the announcement here ([Done](https://github.com/cajuncoding/GraphQL.AzureFunctionsProxy#update-announcement----deprecated-as-of-v13) ✅) and to share a migration guide with those that might be upgrading (also [Done](https://github.com/cajuncoding/GraphQL.AzureFunctionsProxy/blob/main/migrate_to_hc_v13.md) ✅).

**Comment by randyDarsh** [comment]
I'm not sure if this is best place to put this, but I'm still having an issue with upgrading to HC v13.  

I made the changes to the query function, but I'm getting an error on the type being passed into the actual queries.  It appears that it thinks that my Function App is in IN-PROCESS mode, then I'm ISOLATED mode.  If this is the correct place to put this, please let me know and I'll move it.

![image](https://github.com/cajuncoding/GraphQL.AzureFunctionsProxy/assets/5272619/46af8e1d-e845-49be-aaf8-7dc2a903d663)

**Comment by cajuncoding** [comment]
Yeah this isn't the right place since this GitHub is not HotChocolates official repo and as stated above this project will only support v11 & v12. 

You can also post your question into HC Slack channel `#azure-function` which is more appropriate for support.

So are you using v13 as shown in the isolated process VS Template:
https://chillicream.com/blog/2023/02/08/new-in-hot-chocolate-13#azure-functions

**Comment by randyDarsh** [comment]
I'll post the question over on Slack. As for the templates, since this is an existing project, and I was just attempting to upgrade the version I didn't think I needed to install the templates.

**Comment by cajuncoding** [comment]
You don't, but the templates show you how to correctly use the new Official implementation with proper dependencies, etc. 🙂

**Comment by randyDarsh** [comment]
After leaving the previous comment, I realized that what you meant. Thanks for the help.
